# Generated by Django 5.1 on 2024-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RickAndMorty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Personagem')),
                ('genero', models.CharField(max_length=10, verbose_name='Gênero do Personagem')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='Vivo ou Morto')),
                ('especie', models.CharField(max_length=20, verbose_name='Especie do Personagem')),
                ('origem', models.CharField(max_length=60, verbose_name='Origem do Personagem')),
                ('localizacao', models.CharField(blank=True, max_length=60, verbose_name='Localização do Personagem')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
            },
        ),
    ]
